// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLC8f8DdlViXDZd_G4sdqSnaRaqC6fb4Y',
    appId: '1:684605112826:web:b186a0f486f75e3aaca443',
    messagingSenderId: '684605112826',
    projectId: 'tiktok-clone-34666',
    authDomain: 'tiktok-clone-34666.firebaseapp.com',
    storageBucket: 'tiktok-clone-34666.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC36s2FdfVzSI7q8Y75ZRZYWRq4cY25OPs',
    appId: '1:684605112826:android:069d1ccb158477faaca443',
    messagingSenderId: '684605112826',
    projectId: 'tiktok-clone-34666',
    storageBucket: 'tiktok-clone-34666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB63ALZmu0a5qV0ZwkbazrNuIRQC64fiDs',
    appId: '1:684605112826:ios:651ef40268782e90aca443',
    messagingSenderId: '684605112826',
    projectId: 'tiktok-clone-34666',
    storageBucket: 'tiktok-clone-34666.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );
}
